
/*
 * generated by Xtext
 */
 
package fr.univartois.cril.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class AlsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return fr.univartois.cril.xtext.ui.activator.AlsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return fr.univartois.cril.xtext.ui.activator.AlsActivator.getInstance().getInjector("fr.univartois.cril.xtext.Als");
	}
	
}
