/*
* generated by Xtext
*/
package fr.univartois.cril.xtext2.ui.contentassist;

import fr.univartois.cril.xtext2.ui.contentassist.AbstractAlsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AlsProposalProvider extends AbstractAlsProposalProvider {

}
