/*
 * generated by Xtext
 */
package fr.univartois.cril.xtext.scoping;

import java.awt.List;
import java.util.ArrayList;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.scoping.impl.SimpleScope;

import fr.univartois.cril.xtext.als.Decl;
import fr.univartois.cril.xtext.als.Expression;
import fr.univartois.cril.xtext.als.Fact;
import fr.univartois.cril.xtext.als.Function;
import fr.univartois.cril.xtext.als.PropertyName;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class AlsScopeProvider extends AbstractDeclarativeScopeProvider {
	
	/*public IScope scope_Expression_nameRef(Fact context,EReference reference){
		IScope scope = super.getScope(context, reference);
		scope.get
		Block block ;
		List<IE> newScope=new ArrayList<IScopedElement>();
		block = context.getBlock();
		System.out.println(context.getFactName());
		if(block != null){
			//System.out.println(block.getExprB().size());
			for(Expression expression : block.getExprB()){
				if(expression == null) continue;
				System.out.println("common= "+expression.getCommon());
				for(Decl decl : expression.getDecl()){
					if(decl == null) continue;
					System.out.println("pr");
					for(PropertyName property : decl.getPropertyName()){
						System.out.println(property.getName());
					}
				}
			}
		}
		return new SimpleScope(scope,newScope);
	}
	
	public IScope scope_Expression_nameRef(Function context,EReference reference){
		IScope scope = super.getScope(context, reference);
		List<IScopedElement> newScope=new ArrayList<IScopedElement>();
		for(Decl decl : context.getDecl()){
			if(decl == null) continue;
			for(PropertyName propertyName : decl.getPropertyName()){
				if(propertyName == null) continue;
				newScope.add(ScopedElement.create(propertyName.getName(), propertyName));
			}
		}
		return new SimpleScope(scope, newScope);
	}*/
}
