<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="basics"
    nsURI="http://www.univartois.fr/cril/alloyplugin/Basics" nsPrefix="basics">
  <eClassifiers xsi:type="ecore:EClass" name="Specification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//Module"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="open" upperBound="-1" eType="#//Open"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paragraph" upperBound="-1"
        eType="#//Paragraph" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleName" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suite" eType="#//Name"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Open">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Ref" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref2" upperBound="-1" eType="#//Ref"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name2" eType="#//Name"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fact" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="factName" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//BlockBis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertName" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//BlockBis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Ref" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="funName" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl" eType="#//Decl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl2" upperBound="-1"
        eType="#//Decl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//BlockBis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predicate" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pred" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Ref" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predName" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl" eType="#//Decl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl2" upperBound="-1"
        eType="#//Decl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//BlockBis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunCommand" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="runName" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="run" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name2" eType="#//Name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//BlockBis"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//Scope"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckCommand" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkName" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="check" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name2" eType="#//Name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//BlockBis"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//Scope"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typescope" eType="#//Typescope"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Typescope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="n" eType="#//Name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumDecl" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumName" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name2" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name3" upperBound="-1"
        eType="#//Name" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sigName" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name2" upperBound="-1"
        eType="#//Name" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sigExt" eType="#//SigExt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl" eType="#//Decl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl2" upperBound="-1"
        eType="#//Decl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//BlockBis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SigExt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Ref" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref2" upperBound="-1" eType="#//Ref"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//BlockOrBar #//BlockOrBarBis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprT" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrowOp" eType="#//ArrowOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl" eType="#//Decl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//BlockOrBarBis"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameRef" eType="#//Name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockOrBar" eType="#//BlockOrBar"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suite" upperBound="-1"
        eType="#//Name" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprDecl" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decl2"/>
  <eClassifiers xsi:type="ecore:EClass" name="LetDecl" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="letDecl" eType="#//LetDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockOrBarBis" eType="#//BlockOrBarBis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrowOp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="s" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Expression #//BlockBis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" upperBound="-1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockBis" eSuperTypes="#//BlockOrBar #//BlockOrBarBis"/>
  <eClassifiers xsi:type="ecore:EClass" name="BlockOrBar"/>
  <eClassifiers xsi:type="ecore:EClass" name="BlockOrBarBis"/>
  <eClassifiers xsi:type="ecore:EClass" name="Name" eSuperTypes="#//Decl2 #//LetDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprDecl" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprLet" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="this" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameComplete" eType="#//NameBis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameBis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ref">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name"/>
  </eClassifiers>
</ecore:EPackage>
