/*
 * generated by Xtext
 */
package fr.univartois.cril.xtext2.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.univartois.cril.xtext2.ui.internal.AlsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AlsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AlsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AlsActivator.getInstance().getInjector(AlsActivator.FR_UNIVARTOIS_CRIL_XTEXT2_ALS);
	}
	
}
