/*
* generated by Xtext
*/
package fr.univartois.cril.alloyplugin.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BasicsProposalProvider extends AbstractBasicsProposalProvider {

}
