/*
 * generated by Xtext
 */
package fr.univartois.cril.xtext2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.ui.views.contentoutline.IContentOutlinePage;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.DefaultAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import fr.univartois.cril.xtext2.ui.contentassist.AlsProposalProvider;
import fr.univartois.cril.xtext2.ui.documentation.AlsEObjectDocumentationProvider;
import fr.univartois.cril.xtext2.ui.documentation.AlsEObjectHoverProvider;
import fr.univartois.cril.xtext2.ui.outline.AlloyOutlinePage;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AlsUiModule extends
		fr.univartois.cril.xtext2.ui.AbstractAlsUiModule {

	public AlsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IHighlightingConfiguration> bindISemanticHighlightingConfiguration() {
		return HighlightingConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return SemanticHighlightingCalculator.class;
	}

	public Class<? extends DefaultAntlrTokenToAttributeIdMapper> bindDefaultAntlrTokenToAttributeIdMapper() {
		return TokenToIdMapper.class;
	}

	public Class<? extends IContentOutlinePage> bindIContentOutlinePage() {
		return AlloyOutlinePage.class;
	}

	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return AlsEObjectHoverProvider.class;
	}

	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider() {
		return AlsEObjectDocumentationProvider.class;
	}

	public Class<? extends AlsProposalProvider> bindIAlsProposalProvider() {
		return AlsProposalProvider.class;
	}

}
