/*
 * generated by Xtext
 */
package fr.univartois.cril.alloyplugin.labeling;

import org.eclipse.xtext.ui.core.DefaultLabelProvider;

import fr.univartois.cril.alloyplugin.basics.AssertDecl;
import fr.univartois.cril.alloyplugin.basics.CheckDecl;
import fr.univartois.cril.alloyplugin.basics.EnumDecl;
import fr.univartois.cril.alloyplugin.basics.FactDecl;
import fr.univartois.cril.alloyplugin.basics.FunDecl;
import fr.univartois.cril.alloyplugin.basics.Module;
import fr.univartois.cril.alloyplugin.basics.PredDecl;
import fr.univartois.cril.alloyplugin.basics.RunDecl;
import fr.univartois.cril.alloyplugin.basics.SigDecl;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class BasicsLabelProvider extends DefaultLabelProvider {
	/*
	 * 
	 * //Labels and icons can be computed like this:
	 * 
	 * String text(MyModel ele) { return "my "+ele.getName(); }
	 * 
	 * String image(MyModel ele) { return "MyModel.gif"; }
	 */
	/*
	 * String text(Module module) { return module.getName().getName(); }
	 */
	/*String text(Module module){
	
	}*/

	String image(Module module) {
		return "module.gif";
	}

	String image(SigDecl sig) {
		return "sig.gif";
	}

	String image(FactDecl fact) {
		return "fact.gif";
	}

	String image(AssertDecl assertD) {
		return "assert.gif";
	}

	String image(FunDecl fun) {
		return "function.gif";
	}

	String image(PredDecl fun) {
		return "predicate.gif";
	}

	String image(RunDecl run) {
		return "run.gif";
	}

	String image(CheckDecl check) {
		return "check.gif";
	}

	String image(EnumDecl enumD) {
		return "sig.gif";
	}

}
