/*
 * generated by Xtext
 */
package fr.univartois.cril.alloyplugin.labeling;

import org.eclipse.xtext.ui.core.DefaultLabelProvider;

import fr.univartois.cril.alloyplugin.basics.Assertion;
import fr.univartois.cril.alloyplugin.basics.CheckCommand;
import fr.univartois.cril.alloyplugin.basics.EnumDecl;
import fr.univartois.cril.alloyplugin.basics.Fact;
import fr.univartois.cril.alloyplugin.basics.Function;
import fr.univartois.cril.alloyplugin.basics.Module;
import fr.univartois.cril.alloyplugin.basics.Predicate;
import fr.univartois.cril.alloyplugin.basics.RunCommand;
import fr.univartois.cril.alloyplugin.basics.Signature;
import fr.univartois.cril.alloyplugin.basics.Specification;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class BasicsLabelProvider extends DefaultLabelProvider {
	/*
	 * 
	 * //Labels and icons can be computed like this:
	 * 
	 * String text(MyModel ele) { return "my "+ele.getName(); }
	 * 
	 * String image(MyModel ele) { return "MyModel.gif"; }
	 */
	/*
	 * String text(Module module) { return module.getName().getName(); }
	 */
	String text(Specification spec) {
		// return spec.getModule().getModuleName().getName();
		return spec.getModule().getModule().getName();
	}

	String image(Specification spec) {
		return "module.gif";
	}

	String text(Module module){
		return module.getModule().getName();
	}

	String image(Module module) {
		return "module.gif";
	}

	String text(Signature sig) {
		return sig.getSignatureName().get(0).getName();
	}

	String image(Signature sig) {
		return "sig.gif";
	}

	String text(Fact fact){
		return fact.getFactName().getName();
	}

	String image(Fact fact) {
		return "fact.gif";
	}

	String text(Assertion assertD) {
		return assertD.getAssertonName().getName();
	}

	String image(Assertion assertD) {
		return "assert.gif";
	}

	String text(Function fun) {
		return fun.getFunctionName().getName();
	}

	String image(Function fun) {
		return "function.gif";
	}

	String text(Predicate pred) {
		return pred.getPredicateName().getName();
	}

	String image(Predicate fun) {
		return "predicate.gif";
	}

	String text(RunCommand run) {
		return run.getRunName().getName().getName();
	}

	String image(RunCommand run) {
		return "run.gif";
	}

	String text(CheckCommand check) {
		return check.getCheckName().getName().getName();
	}

	String image(CheckCommand check) {
		return "check.gif";
	}

	String text(EnumDecl enumD) {
		return enumD.getEnumName().getName();
	}

	String image(EnumDecl enumD) {
		return "sig.gif";
	}

}
