/*
 * generated by Xtext
 */
package fr.univartois.cril.xtext2.ui.outline;

import org.eclipse.core.runtime.IAdaptable;
import org.eclipse.core.runtime.Platform;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

import fr.univartois.cril.xtext2.als.Specification;

/**
 * customization of the default outline structure
 * 
 */
public class AlsOutlineTreeProvider extends DefaultOutlineTreeProvider implements IAdaptable {

	protected void _createChildren(DocumentRootNode parentNode,
			Specification specification) {
		for (EObject e : specification.eContents()) {
			createNode(parentNode, e);
		}
	}
	
	protected boolean _isLeaf(EObject o) {
		return true;
	}
	
	public Object getAdapter(Class adapter) {
		System.out.println("Adapting "+adapter);
		return  Platform.getAdapterManager().getAdapter(this, adapter);
	}
}
