/*
* generated by Xtext
*/
package fr.univartois.cril.xtext2.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class AlsOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
