/*
* generated by Xtext
*/
package fr.univartois.cril.xtext.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AlsProposalProvider extends AbstractAlsProposalProvider {


}
