/*
 * generated by Xtext
 */
package fr.univartois.cril.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AlsUiModule extends fr.univartois.cril.xtext.ui.AbstractAlsUiModule {
	public AlsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	
}
