/*
 * generated by Xtext
 */
package fr.univartois.cril.alloyplugin.labeling;

import org.eclipse.xtext.ui.core.DefaultLabelProvider;

import fr.univartois.cril.alloyplugin.basics.Assertion;
import fr.univartois.cril.alloyplugin.basics.CheckCommand;
import fr.univartois.cril.alloyplugin.basics.EnumDecl;
import fr.univartois.cril.alloyplugin.basics.Fact;
import fr.univartois.cril.alloyplugin.basics.Function;
import fr.univartois.cril.alloyplugin.basics.Module;
import fr.univartois.cril.alloyplugin.basics.Open;
import fr.univartois.cril.alloyplugin.basics.Predicate;
import fr.univartois.cril.alloyplugin.basics.RunCommand;
import fr.univartois.cril.alloyplugin.basics.Signature;
import fr.univartois.cril.alloyplugin.basics.SignatureName;
import fr.univartois.cril.alloyplugin.basics.Specification;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class BasicsLabelProvider extends DefaultLabelProvider {
	
	String image(Specification spec) {
		return "module.gif";
	}

	String text(Module module){
		return module.getModuleName().getName();
	}
	
	String text(Open open){
		return open.getOpenName().getName();
	}

	String image(Module module) {
		return "module.gif";
	}

	String text(Signature sig) {
		String name = sig.getSignatureName().get(0).getName();
		for(SignatureName n : sig.getSignatureName().subList(1, sig.getSignatureName().size()))
			name+=", "+n.getName();
		return name;
	}

	String image(Signature sig) {
		return "sig.gif";
	}

	String text(Fact fact){
		return fact.getFactName().getName();
	}

	String image(Fact fact) {
		return "fact.gif";
	}

	String text(Assertion assertD) {
		return assertD.getAssertonName().getName();
	}

	String image(Assertion assertD) {
		return "assert.gif";
	}

	String text(Function fun) {
		return fun.getFunctionName().getName();
	}

	String image(Function fun) {
		return "function.gif";
	}

	String text(Predicate pred) {
		return pred.getPredicateName().getName();
	}

	String image(Predicate fun) {
		return "predicate.gif";
	}

	String text(RunCommand run) {
		return run.getRunName().getName();
	}

	String image(RunCommand run) {
		return "run.gif";
	}

	String text(CheckCommand check) {
		return check.getCheckName().getName();
	}

	String image(CheckCommand check) {
		return "check.gif";
	}

	String text(EnumDecl enumD) {
		return enumD.getEnumName().getName();
	}

	String image(EnumDecl enumD) {
		return "sig.gif";
	}

}
