/*
 * generated by Xtext
 */
package fr.univartois.cril.alloyplugin.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class BasicsFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		fr.univartois.cril.alloyplugin.services.BasicsGrammarAccess f = (fr.univartois.cril.alloyplugin.services.BasicsGrammarAccess) getGrammarAccess();

		//...
	}
}
