/*
* generated by Xtext
*/
package fr.univartois.cril.alloyplugin.outline;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.common.editor.outline.ContentOutlineNode;
import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

import fr.univartois.cril.alloyplugin.basics.Specification;

/**
 * customization of the default outline structure
 * 
 */
public class BasicsTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
	@Override
	protected List<EObject> getChildren(EObject semanticNode) {
		if(semanticNode instanceof Specification)
			return semanticNode.eContents();
		return NO_CHILDREN;
	}

	public ContentOutlineNode createNode(Specification semanticNode, ContentOutlineNode parentNode) {	    
	    return HIDDEN_NODE;
	}
}
