/*
* generated by Xtext
*/
package fr.univartois.cril.alloyplugin.outline;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

import fr.univartois.cril.alloyplugin.basics.Module;

/**
 * customization of the default outline structure
 * 
 */
public class BasicsTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
	public List<EObject> getChildren(Module module){
		return NO_CHILDREN;
	}
}
