/*
* generated by Xtext
*/
package fr.univartois.cril.alloyplugin.parser.antlr;

import org.antlr.runtime.ANTLRInputStream;
import org.eclipse.xtext.parser.antlr.ITokenDefProvider;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import fr.univartois.cril.alloyplugin.services.BasicsGrammarAccess;

public class BasicsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject 
    protected ITokenDefProvider antlrTokenDefProvider;
	
	@Inject
	private BasicsGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, ANTLRInputStream in) {
		fr.univartois.cril.alloyplugin.parser.antlr.internal.InternalBasicsLexer lexer = new fr.univartois.cril.alloyplugin.parser.antlr.internal.InternalBasicsLexer(in);
		XtextTokenStream stream = new XtextTokenStream(lexer, antlrTokenDefProvider);
		stream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_COMMENT");
		fr.univartois.cril.alloyplugin.parser.antlr.internal.InternalBasicsParser parser = new fr.univartois.cril.alloyplugin.parser.antlr.internal.InternalBasicsParser(
				stream, getElementFactory(), grammarAccess);
		parser.setTokenTypeMap(antlrTokenDefProvider.getTokenDefMap());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Specification";
	}
	
	public BasicsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BasicsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
