/*
* generated by Xtext
*/
package fr.univartois.cril.alloyplugin.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BasicsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/univartois/cril/alloyplugin/parser/antlr/internal/InternalBasics.tokens");
	}
}
