/*
* generated by Xtext
*/
package fr.univartois.cril.xtext.ui.outline;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.ContentOutlineNode;
import org.eclipse.xtext.ui.editor.outline.actions.IActionBarContributor;
import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

import fr.univartois.cril.xtext.als.Specification;

/**
 * customization of the default outline structure
 * 
 */
public class AlsTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
	@Override
	protected List<EObject> getChildren(EObject semanticNode) {
		if(semanticNode instanceof Specification)
			return semanticNode.eContents();
		return NO_CHILDREN;
	}

	
	public String createNode(Specification semanticNode, ContentOutlineNode parentNode) {	    
	    return INVISIBLE_ROOT_NODE;
	}
	
}
