/*
* generated by Xtext
*/
package fr.univartois.cril.xtext2;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AlsUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.univartois.cril.xtext2.ui.internal.AlsActivator.getInstance().getInjector("fr.univartois.cril.xtext2.Als");
	}
	
}
