/*
 * generated by Xtext
 */
package fr.univartois.cril.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlsRuntimeModule extends fr.univartois.cril.xtext.AbstractAlsRuntimeModule {

}
