/*
 * generated by Xtext
 */
package fr.univartois.cril.xtext;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.ImportUriResolver;

import fr.univartois.cril.xtext.als.uri.AlsConverters;
import fr.univartois.cril.xtext.scoping.AlsScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlsRuntimeModule extends fr.univartois.cril.xtext.AbstractAlsRuntimeModule {
	
	
	
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return AlsConverters.class;
	}
	
	public Class<? extends ImportUriResolver> bindImportUriResolver(){
		return fr.univartois.cril.xtext.als.uri.AlsImportUriResolver.class;
	}
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		
		return AlsScopeProvider.class;
	}
}
