/*
 * generated by Xtext
 */
package fr.univartois.cril.alloyplugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BasicsUiModule extends fr.univartois.cril.alloyplugin.AbstractBasicsUiModule {

}
